"""add teams: roles, member_invites, user ownership

Revision ID: 0f606b031491
Revises: 8a0ccba76690
Create Date: 2026-08-18 18:52:48.705822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f606b031491'
down_revision: Union[str, Sequence[str], None] = '8a0ccba76690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_team_owner_id'), 'roles', ['team_owner_id'], unique=False)
    op.create_table('member_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_invites_owner_id'), 'member_invites', ['owner_id'], unique=False)
    op.create_index(op.f('ix_member_invites_phone_number'), 'member_invites', ['phone_number'], unique=False)
    op.create_index(op.f('ix_member_invites_role_id'), 'member_invites', ['role_id'], unique=False)
    op.add_column('content_jobs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_content_jobs_created_by'), 'content_jobs', ['created_by'], unique=False)
    op.create_foreign_key(None, 'content_jobs', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_owner_user_id'), 'users', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_owner_user_id'), table_name='users')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'owner_user_id')
    op.drop_constraint(None, 'content_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_content_jobs_created_by'), table_name='content_jobs')
    op.drop_column('content_jobs', 'created_by')
    op.drop_index(op.f('ix_member_invites_role_id'), table_name='member_invites')
    op.drop_index(op.f('ix_member_invites_phone_number'), table_name='member_invites')
    op.drop_index(op.f('ix_member_invites_owner_id'), table_name='member_invites')
    op.drop_table('member_invites')
    op.drop_index(op.f('ix_roles_team_owner_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
