"""hardening: audit log, otp ip tracking, idempotency key

Revision ID: 8a0ccba76690
Revises: 3347278f8feb
Create Date: 2026-08-13 00:06:21.792858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0ccba76690'
down_revision: Union[str, Sequence[str], None] = '3347278f8feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.add_column('content_jobs', sa.Column('client_idempotency_key', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_content_jobs_client_idempotency_key'), 'content_jobs', ['client_idempotency_key'], unique=True)
    op.add_column('otp_codes', sa.Column('ip_address', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'ip_address')
    op.drop_index(op.f('ix_content_jobs_client_idempotency_key'), table_name='content_jobs')
    op.drop_column('content_jobs', 'client_idempotency_key')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
